name: Deploy Slide

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn workspace @docs/slidev build

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/slidev/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
